### PR TITLE
Properly set post type param to fix issues with Polylang and possibly others.

### PR DESCRIPTION
**Pull request by JoryHogeveen**
Second try PR :) Prev: #109

> Setting the post type to any can cause edge case issues with other plugins and WP core.
>
> For non-translatable post types this will create compatibility issues with Polyland since adding any will trigger Polylang to add the language queries, even though the ID's might not be translatable.
>
>Other than that, setting any also affects WP default query to only include public posts. I can imagine edge cases where this might cause issues.

Added enhancement to the above for relationship fields.

### CODE REVIEW

**Comment by quasel** [comment]
looks god so far - but I'm a bit out of the loop ;) - hope to help out more soon again! 

@sc0ttkclark any objections?

**Comment by quasel** [comment]
oh and if I remember correctly we should create a branch for the next release that then get's merged into main…

**Comment by JoryHogeveen** [comment]
@quasel No problem, maybe you can create a branche and name it as you like, perhaps the version number or just `dev`?

**Comment by JoryHogeveen** [comment]
@quasel @sc0ttkclark 
Let me know if there is anything else you need from me. It's been a while since the latest update from this plugin so I think this would be a good addition for compatibility.

**Review by sc0ttkclark — APPROVED** [review]

**Pull request merged**
